routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PemasukanController;
use App\Http\Controllers\PengeluaranController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DasbortController;
use App\Http\Controllers\OtentikasiController;
use App\Http\Middleware\CekLoginMiddleware;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [OtentikasiController::class, 'index'])->name('login');
Route::post('login', [OtentikasiController::class, 'login'])->name('login');

Route::group(['middleware' => 'CekLoginMiddleware'], function(){
    Route::resource('dasbort', DasbortController::class);
    Route::resource('pemasukan', PemasukanController::class);
    Route::resource('pengeluaran', PengeluaranController::class);
    Route::resource('pengguna', PenggunaController::class);
    Route::get('pengguna/kabupaten/{id}',[PenggunaController::class, 'kabupaten']);
    Route::get('pengguna/kecamatan/{id}',[PenggunaController::class, 'kecamatan']);
    Route::get('pengguna/desa/{id}',[PenggunaController::class, 'desa']);
    Route::get('logout',  [OtentikasiController::class, 'logout'])->name('logout');
});

app/Models/Pengguna.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Carbon;

class Pengguna extends Model
{
    use HasFactory;
    protected $table = 'pengguna';
    public $timestamps = true;

    // protected $casts = [
    //     'id_transaksi' => 'string'
    // ];

    protected $fillable = ['id_user', 'nama_pengguna', 'username', 'password', 'kd_provinsi', 'kd_kabupaten', 'kd_kecamatan', 'kd_desa', 'foto', 'barcod']; //atribut tabel
    protected $primaryKey = 'id_user';

    public static function kode_otomatis()
    {
        $q = DB::table('pengguna')->SELECT(DB::raw("MAX(RIGHT(id_user,4)) AS kd_max"));
        $kd = "";
        if ($q) {
            foreach ($q->get() as $k) {
                $tmp = ((int)$k->kd_max) + 1;
                $kd = sprintf("%04s", $tmp);
            }
        } else {
            $kd = "0001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return date('dmY') . $kd;
    }
    //tanggal indonesia gelobal
    public function getCreatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])
        ->format('d, M Y H:i');
    }

    public static function getJoin($id)
    {
        $query = DB::table('pengguna')->select(DB::raw('*'))->join('wilayah_provinsi', 'kd_provinsi', '=', 'wilayah_provinsi.id')
                    ->join('wilayah_kabupaten', 'kd_kabupaten', '=', 'wilayah_kabupaten.id')
                    ->join('wilayah_kecamatan', 'kd_kecamatan', '=', 'wilayah_kecamatan.id')
                    ->join('wilayah_desa', 'kd_desa', '=', 'wilayah_desa.id')->where('id_user',$id)->get();
        return $query;
    }
    public static function getProvinsi()
    {
        $query = DB::table('wilayah_provinsi')->select('*')->get();
        return $query;
    }
    public static function getKabupaten($id)
    {
        $query = DB::table('wilayah_kabupaten')->where('provinsi_id',$id)->get();
        return $query;
    }
    public static function getKecamatan($id)
    {
        $query = DB::table('wilayah_kecamatan')->where('kabupaten_id',$id)->get();
        return $query;
    }
    public static function getDesa($id)
    {
        $query = DB::table('wilayah_desa')->where('kecamatan_id',$id)->get();
        return $query;
    }
}

app/Http/Controllers/PenggunaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengguna;
use Illuminate\Http\Request;

class PenggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengguna = Pengguna::join('wilayah_provinsi', 'kd_provinsi', '=', 'wilayah_provinsi.id')
                    ->join('wilayah_kabupaten', 'kd_kabupaten', '=', 'wilayah_kabupaten.id')
                    ->join('wilayah_kecamatan', 'kd_kecamatan', '=', 'wilayah_kecamatan.id')
                    ->join('wilayah_desa', 'kd_desa', '=', 'wilayah_desa.id')->paginate(10);
        return view('pengguna.index', compact('pengguna'))
        ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pengguna = Pengguna::kode_otomatis();
        $provinsi = Pengguna::getProvinsi();
        return view('pengguna.create', compact('provinsi','pengguna'));
    }

    public function kabupaten($id){
         //$id = $request->id;
        $data = Pengguna::getKabupaten($id);
        return response()->json($data);
    }

    public function kecamatan($id){
        //$id = $request->id;
       $data = Pengguna::getKecamatan($id);
       return response()->json($data);
    }
    public function desa($id){
        //$id = $request->id;
        $data = Pengguna::getDesa($id);
        return response()->json($data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required',
            'username' => 'required',
            'password' => 'required',
            // 'kd_provinsi' => 'required',
            // 'kd_kabupaten' => 'required',
            // 'kd_kecamatan' => 'required',
            // 'kd_desa' => 'required',
            'foto' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:10048',
         ]);

        $file = $request->file('foto');
        $nama_file = $file->getClientOriginalName();
        $extensi_file = $file->getClientOriginalExtension();
        $tujuan_upload = 'Data_file_Pengguna';
        $file->move($tujuan_upload,$nama_file,$extensi_file);

         Pengguna::create([
            'id_user' => $request->id_user,
            'nama_pengguna'=> $request->nama,
            'username'=> $request->username,
            'password'=> md5($request->password),
            'kd_provinsi' => $request->provinsi,
            'kd_kabupaten'=> $request->kabupaten,
            'kd_kecamatan' => $request->kecamatan,
            'kd_desa' => $request->kelurahan,
            'foto' => $nama_file,$extensi_file,
            'barcod' => 'default.jpg'
         ]);
         return redirect()->route('pengguna.index')
            ->with('success', 'Project created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function show(Pengguna $pengguna)
    {
        $pengguna = Pengguna::getJoin($pengguna->id_user);
        return view('pengguna.show',compact('pengguna'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengguna $pengguna)
    {
        $pengguna = Pengguna::getJoin($pengguna->id_user);
        $provinsi = Pengguna::getProvinsi();
        return view('pengguna.edit',compact('provinsi','pengguna'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pengguna $pengguna)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pengguna  $pengguna
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengguna $pengguna)
    {
        $pengguna->delete();

        return redirect()->route('pengguna.index')
            ->with('success', 'Project deleted successfully');

    }
}

resources/views/pengguna/create.blade.php
@extends('Layout.template')
@section('content')
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-colored-form-control">Data Pengguna</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                            <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                            <li><a data-action="close"><i class="icon-cross2"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <form class="form" action="{{route('pengguna.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_user">ID Pengguna</label>
                                    <input type="text" class="form-control" id="id_user" name="id_user" value="{{$pengguna}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="userinput2">Nama</label>
                                    <input type="text" class="form-control " id="nama" name="nama" autofocus value="<?= old('nama'); ?>">
                                    @if ($errors->has('nama'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('nama') }}
                                    </div>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>Provinsi</label>
                                    <select class="form-control " name="provinsi" id="provinsi">
                                        <option value=""> Pilih Provinsi</option>
                                        @foreach ($provinsi as $provinsi)
                                        <option value="{{$provinsi->id}}">{{$provinsi->nama_provinsi}}</option>
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kabupaten</label>
                                    <select class="form-control " name="kabupaten" id="kabupaten">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kecamatan</label>
                                    <select class="form-control " name="kecamatan" id="kecamatan">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kelurahan</label>
                                    <select class="form-control " name="kelurahan" id="kelurahan">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="userinput6">Username</label>
                                    <input type="text" class="form-control " id="username" name="username" value="<?= old('username'); ?>">
                                    @if ($errors->has('username'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('username') }}
                                    </div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="userinput6">Password</label>
                                    <input type="password" class="form-control " id="password" name="password" value="<?= old('password'); ?>">
                                    @if ($errors->has('password'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('password') }}
                                    </div>
                                    @endif
                                </div>

                                <div class="form-group row">
                                    <label for="foto" class="col-sm-2 col-form-label">Foto</label>
                                    <div class="col-sm-6">
                                        <img src="/app-assets/images/user.jpg" class="img-thumbnail img-preview" style="position: relative; height:200px;">
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="custom-file">
                                            <label class="file center-block" for="foto">
                                                <input type="file" class="custom-file-input " id="foto" name="foto" onchange="previewImg2()">
                                                <label class="custom-file-label btn btn-secondary btn-min-width" style="margin-top: -10%; margin-left:-5%" for="foto">Choose file</label>
                                            </label>
                                            @if ($errors->has('foto'))
                                            <div class="invalid-tooltip" style="color:red;">
                                                    {{ $errors->first('foto') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions right">
                                <a href="/pengguna" class="btn btn-warning"><i class="icon-cross2"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#provinsi').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/kabupaten/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_kabupaten + '</option>';
                    }
                    $('#kabupaten').html(html);

                }
            });
        });
        $('#kabupaten').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/kecamatan/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_kecamatan + '</option>';
                    }
                    $('#kecamatan').html(html);

                }
            });
        });
        $('#kecamatan').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/desa/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_desa + '</option>';
                    }
                    $('#kelurahan').html(html);

                }
            });
        });
    });
</script>
@endsection

resources/views/pengguna/edit.blade.php
@extends('Layout.template')
@section('content')
@foreach ($pengguna as $pengguna)
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-colored-form-control">Data Pengguna</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                            <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                            <li><a data-action="close"><i class="icon-cross2"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                        <form class="form" action="{{route('pengguna.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_user">ID Pengguna</label>
                                    <input type="text" class="form-control" id="id_user" name="id_user" value="{{$pengguna->id_user}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="userinput2">Nama</label>
                                    <input type="text" class="form-control " id="nama" name="nama" autofocus value="{{$pengguna->nama_pengguna}}">
                                </div>

                                <div class="form-group">
                                    <label>Provinsi</label>
                                    <select class="form-control " name="provinsi" id="provinsi">
                                        <option value=""> Pilih Provinsi</option>
                                        @foreach ($provinsi as $provinsi)
                                            @if($provinsi->id == $pengguna->kd_provinsi)
                                            <option value="{{$provinsi->id}}" selected='selected'>{{$provinsi->nama_provinsi}}</option>
                                            @else
                                                <option value="{{$provinsi->id}}">{{$provinsi->nama_provinsi}}</option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kabupaten</label>
                                    <select class="form-control " name="kabupaten" id="kabupaten">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kecamatan</label>
                                    <select class="form-control " name="kecamatan" id="kecamatan">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label>Kelurahan</label>
                                    <select class="form-control " name="kelurahan" id="kelurahan">
                                        <option value="">Pilih</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="userinput6">Username</label>
                                    <input type="text" class="form-control " id="username" name="username" value="<?= old('username'); ?>">
                                    @if ($errors->has('username'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('username') }}
                                    </div>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label for="userinput6">Password</label>
                                    <input type="password" class="form-control " id="password" name="password" value="<?= old('password'); ?>">
                                    @if ($errors->has('password'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('password') }}
                                    </div>
                                    @endif
                                </div>

                                <div class="form-group row">
                                    <label for="foto" class="col-sm-2 col-form-label">Foto</label>
                                    <div class="col-sm-6">
                                        <img src="/app-assets/images/user.jpg" class="img-thumbnail img-preview" style="position: relative; height:200px;">
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="custom-file">
                                            <label class="file center-block" for="foto">
                                                <input type="file" class="custom-file-input " id="foto" name="foto" onchange="previewImg2()">
                                                <label class="custom-file-label btn btn-secondary btn-min-width" style="margin-top: -10%; margin-left:-5%" for="foto">Choose file</label>
                                            </label>
                                            @if ($errors->has('foto'))
                                            <div class="invalid-tooltip" style="color:red;">
                                                    {{ $errors->first('foto') }}
                                            </div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions right">
                                <a href="/pengguna" class="btn btn-warning"><i class="icon-cross2"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#provinsi').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/kabupaten/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_kabupaten + '</option>';
                    }
                    $('#kabupaten').html(html);

                }
            });
        });
        $('#kabupaten').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/kecamatan/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_kecamatan + '</option>';
                    }
                    $('#kecamatan').html(html);

                }
            });
        });
        $('#kecamatan').change(function() {
            var id = $(this).val();
            $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
            });
            $.ajax({
                url: "{{url('pengguna/desa/')}}/"+ $(this).val(),
                method: "GET",
                success: function(data) {
                    console.log(data);
                    var html = '';
                    var i;
                    for (i = 0; i < data.length; i++) {
                        html += '<option value=' + data[i].id + '>' + data[i].nama_desa + '</option>';
                    }
                    $('#kelurahan').html(html);

                }
            });
        });
    });
</script>
@endforeach
@endsection