routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PemasukanController;
use App\Http\Controllers\PengeluaranController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DasbortController;
use App\Http\Controllers\OtentikasiController;
use App\Http\Middleware\CekLoginMiddleware;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [OtentikasiController::class, 'index'])->name('login');
Route::post('login', [OtentikasiController::class, 'login'])->name('login');

Route::group(['middleware' => 'CekLoginMiddleware'], function(){
    Route::resource('dasbort', DasbortController::class);
    Route::resource('pemasukan', PemasukanController::class);
    Route::resource('pengeluaran', PengeluaranController::class);
    Route::resource('pengguna', PenggunaController::class);
    Route::get('pengguna/kabupaten/{id}',[PenggunaController::class, 'kabupaten']);
    Route::get('pengguna/kecamatan/{id}',[PenggunaController::class, 'kecamatan']);
    Route::get('pengguna/desa/{id}',[PenggunaController::class, 'desa']);
    Route::get('logout',  [OtentikasiController::class, 'logout'])->name('logout');
});

app/Models/Pemasukan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Carbon;

class Pemasukan extends Model
{
    use HasFactory;
    protected $table = 'transaksi_kas';
    public $timestamps = true;

    protected $casts = [
        'id_transaksi' => 'string'
    ];

    protected $fillable = ['id_transaksi', 'rincian_transaksi','jumlah','harga','total','jenis_transaksi','struk','created_at']; //atribut tabel
    protected $primaryKey = 'id_transaksi';

    public static function kode_otomatis()
    {
        $q = DB::table('transaksi_kas')->SELECT(DB::raw("MAX(RIGHT(id_transaksi,4)) AS kd_max"));
        $kd = "";
        if ($q) {
            foreach ($q->get() as $k) {
                $tmp = ((int)$k->kd_max) + 1;
                $kd = sprintf("%04s", $tmp);
            }
        } else {
            $kd = "0001";
        }
        date_default_timezone_set('Asia/Jakarta');
        return date('dmY') . $kd;
    }
    //tanggal indonesia gelobal
    public function getCreatedAtAttribute()
    {
        return \Carbon\Carbon::parse($this->attributes['created_at'])
        ->format('d, M Y H:i');
    }

    public static function getJumlahPemasukan()
    {
        $query = DB::table('transaksi_kas')
        ->select(DB::raw('SUM(jumlah) AS pemasukan'),DB::raw('YEAR(created_at) tahun_kas'),DB::raw('MONTH(created_at) bulan_kas'))
        ->where('jenis_transaksi', 'pemasukan')
        ->groupBy(DB::raw('YEAR(created_at)'), DB::raw('MONTH(created_at)'))
        ->get();
        return $query;
    }
}

app/Http/Controllers/PemasukanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pemasukan;
use Illuminate\Http\Request;

class PemasukanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pemasukan = Pemasukan::where('jenis_transaksi', 'pemasukan')->paginate(10);
        //$pemasukan = paginate(10);
        return view('pemasukan.index', compact('pemasukan'));
            //->with('i', (request()->input('page', 1) - 1) * 5);
        //return view('pemasukan.index',['pemasukan' => $pemasukan]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pemasukan = Pemasukan::kode_otomatis();
        return view('pemasukan.create', compact('pemasukan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'rincian_transaksi' => 'required',
           'jumlah' => 'required',
           'kuitansi' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
        ]);

        $file = $request->file('kuitansi');
        $nama_file = $file->getClientOriginalName();
        $extensi_file = $file->getClientOriginalExtension();
        $tujuan_upload = 'Data_file_pemasukan';
        Pemasukan::create([
            'id_transaksi' => $request->id_transaksi,
            'rincian_transaksi' => $request->rincian_transaksi,
            'jumlah' =>$request->jumlah,
            'harga' => 0,
            'total' => 0,
            'jenis_transaksi' => 'pemasukan',
            'struk' =>$nama_file, $extensi_file
        ]);
        $file->move($tujuan_upload,$nama_file,$extensi_file);

        return redirect()->route('pemasukan.index')
            ->with('success', 'Project created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pemasukan  $pemasukan
     * @return \Illuminate\Http\Response
     */
    public function show(Pemasukan $pemasukan)
    {
        return view('pemasukan.show', compact('pemasukan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pemasukan  $pemasukan
     * @return \Illuminate\Http\Response
     */
    public function edit(Pemasukan $pemasukan)
    {
        return view('pemasukan.edit', compact('pemasukan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pemasukan  $pemasukan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pemasukan $pemasukan)
    {
        $file = $request->file('kuitansi');
        $nama_file = $file->getClientOriginalName();
        $extensi_file = $file->getClientOriginalExtension();
        $tujuan_upload = 'Data_file_pemasukan';
        $pemasukan->update([
            'id_transaksi' => $request->id_transaksi,
            'rincian_transaksi' => $request->rincian_transaksi,
            'jumlah' =>$request->jumlah,
            'harga' => 0,
            'total' => 0,
            'jenis_transaksi' => 'pemasukan',
            'struk' =>$nama_file, $extensi_file
        ]);
        $file->move($tujuan_upload,$nama_file,$extensi_file);

        return redirect()->route('pemasukan.index')
            ->with('success', 'Project created successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pemasukan  $pemasukan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pemasukan $pemasukan)
    {
        $pemasukan->delete();

        return redirect()->route('pemasukan.index')
            ->with('success', 'Project deleted successfully');
    }
}

resources/views/pemasukan/create.blade.php
@extends('Layout.template')
@section('content')
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-colored-form-control">Data Tranaksi</h4>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                    <form action="{{ route('pemasukan.store')}}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}     
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_transaksi">ID Transaksi</label>
                                    <input type="text" class="form-control" id="id_transaksi" name="id_transaksi" value="{{$pemasukan}}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="userinput2">Rincian</label>
                                    <input type="text" class="form-control  " id="rincian_transaksi" name="rincian_transaksi" autofocus value="">
                                    @if ($errors->has('rincian_transaksi'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('rincian_transaksi') }}
                                    </div>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label for="userinput3">Jumlah</label>
                                    <input type="text" class="form-control " id="jumlah" name="jumlah" value="<?= old('jumlah'); ?>">
                                    @if ($errors->has('jumlah'))
                                    <div class="invalid-tooltip" style="color:red;">
                                            {{ $errors->first('jumlah') }}
                                    </div>
                                    @endif
                                </div>
                                <div class="form-group row">
                                    <label for="kuitansi" class="col-sm-2 col-form-label">Kuitansi</label>
                                    <div class="col-sm-6">
                                        <img src="/app-assets/images/user.jpg" class="img-thumbnail img-preview" style="position: relative; height:200px;">
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="custom-file">
                                            <label class="file center-block" for="kuitansi">
                                                <input type="file" class="custom-file-input  " id="kuitansi" name="kuitansi" onchange="previewImg()">
                                                <label class="custom-file-label btn btn-secondary btn-min-width" style="margin-top: -10%; margin-left:-5%" for="kuitansi">Choose file</label>
                                            </label>
                                            @if ($errors->has('kuitansi'))
                                            <div class="invalid-tooltip" style="color:red;">
                                                    {{ $errors->first('kuitansi') }}
                                            </div>
                                            @endif      
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions right">
                                <a href="{{ route('pemasukan.index') }}"class="btn btn-warning"><i class="icon-cross2"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                                                              
                            </div>
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemasukan/edit.blade.php
@extends('Layout.template')
@section('content')
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-colored-form-control">Data Tranaksi</h4>
                </div>
                <div class="card-body collapse in">
                    <div class="card-block">
                    <form action="{{ route('pemasukan.update',$pemasukan->id_transaksi)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')     
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_transaksi">ID Transaksi</label>
                                    <input type="text" class="form-control" id="id_transaksi" name="id_transaksi" value="{{ $pemasukan->id_transaksi }}" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="userinput2">Rincian</label>
                                    <input type="text" class="form-control " id="rincian_transaksi" name="rincian_transaksi" autofocus value="{{ $pemasukan->rincian_transaksi }}">
                                    <div class="invalid-tooltip" style="color:red;">
        
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="userinput3">Jumlah</label>
                                    <input type="text" class="form-control " id="jumlah" name="jumlah" value="{{ $pemasukan->jumlah }}">
                                    <div class="invalid-tooltip" style="color:red;">
                                       
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="kuitansi" class="col-sm-2 col-form-label">Kuitansi</label>
                                    <div class="col-sm-6">
                                        <img src="/Data_file_Pemasukan/{{$pemasukan->struk}}" class="img-thumbnail img-preview" style="position: relative; height:200px;">
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="custom-file">
                                            <label class="file center-block" for="kuitansi">
                                                <input type="file" class="custom-file-input  " id="kuitansi" name="kuitansi" onchange="previewImg()">
                                                <label class="custom-file-label btn btn-secondary btn-min-width" style="margin-top: -10%; margin-left:-5%" for="kuitansi">Choose file</label>
                                            </label>

                                            <div class="invalid-tooltip" style="color:red;">
                                               
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-actions right">
                                <a href="{{ route('pemasukan.index') }}"class="btn btn-warning"><i class="icon-cross2"></i> Cancel</a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> Save
                                </button>
                                                              
                            </div>
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemasukan/index.blade.php
@extends('Layout.template')
@section('content')
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body">
            <!-- Bordered table start -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="card border-success">
                        <div class="card-header bg-success">
                            <h4 class="card-title" style="color:black;">Data Pemasukan</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="icon-minus4" style="color:black;"></i></a></li>
                                    <li><a data-action="reload"><i class="icon-reload" style="color:black;"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2" style="color:black;"></i></a></li>
                                    <li><a data-action="close"><i class="icon-cross2" style="color:black;"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body collapse in">
                            <div class="table-responsive card-block">
                                <div class="row">
                                    <div class="col-xs-12 col-md-center">
                                        <div class="form-group">
                                            <!-- Single Button Dropdown -->
                                            <div class="btn-group mb-0.1 mr-0.1 " style="float:right;">
                                                <form action="" method="GET">
                                                {{ @csrf_field() }}
                                                    <div class="btn-group" role="group" aria-label="Basic example">
                                                        <fieldset class="form-group position-relative">
                                                            <input type="text" class="form-control" placeholder="Masukan " name="cari">
                                                            <div class="form-control-position " style="margin-right: 9px;">
                                                                <button class="btn btn-outline-primary btn-info mb-2 mr-4 mb-0.1 " type="submit" name="submit">Cari</button>
                                                            </div>
                                                        </fieldset>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <!-- Single Button Dropdown -->
                                            <div class="btn-group mb-0.1 ml-0.1 " style="float:lefth; margin-top:-15px;">
                                                <a href="{{ route('pemasukan.create')}}" class="btn btn-info btn-outline-primary mb-0.1 ">Tambah Data</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <table class="table table-bordered mb-4 ">
                                    <thead>
                                        <tr>
                                            <th scope="col">No</th>
                                            <th scope="col">Rincian</th>
                                            <th scope="col">Jumlah</th>
                                            <th scope="col">Tanggal</th>
                                            <th scope="col">Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php $i=0; ?>
                                    @foreach ($pemasukan as $pemasukan1)
                                    <tr>
                                        <td>{{ ++$i }}</td>
                                        <td>{{ $pemasukan1->rincian_transaksi }}</td>
                                        <td>Rp. {{ number_format($pemasukan1->jumlah,0,',','.') }}</td>
                                        <td>{{ $pemasukan1->created_at}}</td>
                                        <td>
                                            <!-- Button trigger modal -->
                                            <a href="#del{{$pemasukan1->id_transaksi}}" class="btn btn-danger" data-toggle="modal">Hapus </a>


                                            <a href="{{ route('pemasukan.show', $pemasukan1->id_transaksi) }}" class=" btn btn-primary">
                                            Lihat
                                            </a>
                                            <a href="{{ route('pemasukan.edit', $pemasukan1->id_transaksi) }}" class=" btn btn-warning">
                                            Edit
                                            </a>
                                        <!-- Modal -->
                                            <div class="modal fade bd-example-modal-sm" id="del{{$pemasukan1->id_transaksi}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog modal-sm" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Konfirmasi Hapus</h5>
                                                        </div>
                                                        <div class="modal-body" style="text-align: center;">
                                                            Apakah Anda ingin Menghapus Data <b>{{$pemasukan1->id_transaksi}}</b>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                                                            <form action="{{ route('pemasukan.destroy', $pemasukan1->id_transaksi) }}" method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>                 
                                </table> 
                                <div class="d-flex justify-content-center">
                                    {!! $pemasukan->links() !!}
                                </div>                  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pemasukan/show.blade.php
@extends('Layout.template')
@section('content')
<div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title" id="basic-layout-colored-form-control">Detail Transaksi</h4>
                    <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                            <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                            <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                            <li><a data-action="close"><i class="icon-cross2"></i></a></li>
                        </ul>
                    </div>
                </div>
                <!-- stats -->
                <div class="row mt-2 ml-2">
                    <div class="col-xl-5 col-lg-4 col-xs-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-block">
                                    <div class="media">
                                        <div class="media-body text-xs-left">
                                            <img src="/Data_file_Pemasukan/{{$pemasukan->struk}}" alt="" class="img-thumbnail img-preview" width=74%; height="9.9%" style="margin-left:13% ;">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-xs-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-block">
                                    <div class="media">
                                        <div class="media-body text-xs-left">
                                            <div class="form-body">
                                                <div class="form-group">
                                                    <label for="userinput5">ID Transaksi</label>
                                                    <input class="form-control border-primary" type="email" value="{{$pemasukan->id_transaksi}}" disabled>
                                                </div>

                                                <div class="form-group">
                                                    <label for="userinput6">Rincian Transaksi</label>
                                                    <input class="form-control border-primary" type="url" value="{{$pemasukan->rincian_transaksi}}" disabled>
                                                </div>

                                                <div class="form-group">
                                                    <label for="userinput6">Jumlah</label>
                                                    <input class="form-control border-primary" type="url" value="{{$pemasukan->jumlah}}" disabled>
                                                </div>
                                                <div class="form-group">
                                                    <label for="userinput6">Tanggal Pemasukan</label>
                                                    <input class="form-control " type="url" value="{{$pemasukan->created_at}}" disabled>
                                                </div>

                                            </div>
                                            <div class="form-actions" data-toggle="tooltip" data-placement="left" title="Kembali" style="margin-left: 78% ;">
                                                <a href="{{route('pemasukan.index')}}" class="btn btn-warning"><i class="icon-cross2"></i> Kembali</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection